spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gauti2287/obrsconfig-properties.git
server:
  port: 8071    
  profiles:
    active:native
      